# Generated by Django 3.1.3 on 2020-12-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demopost',
            name='excerpt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='demopost',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique_for_date='date_posted'),
        ),
        migrations.AlterField(
            model_name='demopost',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
